import axios from 'axios';

const API_URL = 'http://127.0.0.1:8000';

const api = {
  getChallenge: () => {
    return axios.get(`${API_URL}/users/challenge`);
  },
  
  registerUser: (userData, token) => {
    return axios.post(`${API_URL}/users/register?token=${token}`, userData);
  },
  
  loginUser: (credentials) => {
    // creds to form data as required by OAuth2
    // generated by Claude AI (lines 19:26)
    const formData = new URLSearchParams();
    formData.append('username', credentials.username);
    formData.append('password', credentials.password);
    
    return axios.post(`${API_URL}/users/login`, formData, {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    });
  },
  
  // helper, generated by Claude AI (lines 27:34)
  getCurrentUser: () => {
    const token = localStorage.getItem('authToken');
    return axios.get(`${API_URL}/users/me`, {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    });
  }
};

export default api;